name: integration-tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Integration (${{ matrix.versions.ansible }}) / (${{ matrix.module}})
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ansible: stable-2.18
            python: "3.11"
        module:
          - sshkey_info
          - sshkey
          - server_info
          - server
          - floating_ip_info
          - floating_ip
          - storage_info
          - storage
          - project
          - project_info
    steps:
      - name: Perform testing
       # Hopefully https://github.com/ansible-community/ansible-test-gh-action/pull/121 gets merged and released
       # at some point, so we don't need this fork.
        uses: cherryservers/ansible-test-gh-action@ef40f85a28ca0a14060dab06bb752fb9acea2376 # v1.18.0
        with:
          pre-test-cmd: >-
            CHERRY_AUTH_TOKEN=${{ secrets.CHERRY_AUTH_TOKEN }}
            CHERRY_PROJECT_ID=${{ secrets.CHERRY_PROJECT_ID }}
            CHERRY_BAREMETAL_SERVER_ID=${{ secrets.CHERRY_BAREMETAL_SERVER_ID }}
            CHERRY_TEAM_ID=${{ secrets.CHERRY_TEAM_ID }}
            ./tests/utils/render.sh
            tests/integration/integration_config.yml.template
            > tests/integration/integration_config.yml
          ansible-core-version: ${{ matrix.versions.ansible }}
          origin-python-version: ${{ matrix.versions.python }}
          target: ${{ matrix.module }}
          target-python-version: ${{ matrix.versions.python }}
          testing-type: integration
          integration-retry-on-error: false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}